### ISSUE TITLE
How

### ISSUE THREAD

**Issue by 8amjoker** [natainditama/auctionx#11]
How can I open the admin portal

**Comment by natainditama** [comment]
Hi @8amjoker 

Thank you for your time and for using something I've created. However, I wouldn't recommend using this repository because it's built using native PHP. This project has several security issues, such as SQL injection and others. I use this project for my school assignments, but I suggest using other frameworks like [Laravel ](https://laravel.com/) or [CodeIgniter](https://codeigniter.com/) instead.

Thanks.
